---
- name: Add accounts
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - root
      - sudo
      - ssh
    shell: /bin/bash
  loop:
    - f213
    - samat

- name: Add ssh keys
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  loop:
    - username: f213
      key: https://github.com/f213.keys
    - username: samat
      key: https://github.com/gsamat.keys
  loop_control:
    label: "{{ item.username }}"

- name: Add less secure ssh key
  ansible.posix.authorized_key:
    user: f213
    key: "{{ lookup('file', 'keys/less_secure_ssh_key') }}"
    key_options: "no-pty,command=\"echo No commands please\""

- name: Limit access to only users of _ssh group
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: AllowGroups
    line: AllowGroups ssh
  notify:
    - Reload sshd
